name: create pr

on:      
 workflow_dispatch:

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  create-pr:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5 # v2
        with:
          egress-policy: audit
      - uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5
      - name: Create commits
        run: |
          git config user.name 'Varun'
          git config user.email 'varunsh-coder@users.noreply.github.com'
          date +%s > report.txt
          git add .
          git commit -m "Add untracked file during workflow"
      - name: Uncommitted change
        run: date +%s > report.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@67df31e08a133c6a77008b89689677067fef169e
