name: Docker Image CI

on:
  workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@rc # v2.1.0
      with:
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          api.osv.dev:443
          gcr.io:443
          github.com:443
          storage.googleapis.com:443

    - uses: actions/checkout@v3
    - name: run the Docker image
      run: docker run -e GITHUB_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }} gcr.io/openssf/scorecard:stable --show-details --repo=https://github.com/ossf/scorecard
      
    - run: sudo iptables -L -v -n 
      if: ${{ failure() }}
