name: Policy demo

on: [push, issues, workflow_dispatch]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  harden-runner-demo:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@v2
      with:
        policy: policy1

    - uses: actions/first-interaction@1d8459ca65b335265f1285568221e229d45a995e # v1.1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"

    - run: curl -X GET https://google.com
