name: HardenRunner Test
on: 
  workflow_dispatch
permissions:
  contents: read

jobs:
  block22:
    runs-on: ubuntu-22.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@test
      with:
        egress-policy: block
        allowed-endpoints: >
          github.com:443
          www.google.com:443
          api.github.com:443
          www.microsoft.com:443
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - run: sleep 20
    - run: curl -X GET https://www.google.com
    - run: sleep 20
    - run: curl -X GET https://api.github.com
    - run: sleep 20
    - run: curl -X GET https://www.google.com
    - run: sleep 20
    - run: curl -X GET https://www.microsoft.com/en-us/
  block20:
    runs-on: ubuntu-20.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@test
      with:
        egress-policy: block
        allowed-endpoints: >
          github.com:443
          www.google.com:443
          api.github.com:443
          www.microsoft.com:443
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - run: sleep 20
    - run: curl -X GET https://www.google.com
    - run: sleep 20
    - run: curl -X GET https://api.github.com
    - run: sleep 20
    - run: curl -X GET https://www.google.com
    - run: sleep 20
    - run: curl -X GET https://www.microsoft.com/en-us/
  audit22:
    runs-on: ubuntu-22.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@test
      with:
        egress-policy: audit
        
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - run: sleep 20
    - run: curl -X GET https://www.google.com
    - run: sleep 20
    - run: curl -X GET https://api.github.com
    - run: sleep 20
    - run: curl -X GET https://www.google.com
    - run: sleep 20
    - run: curl -X GET https://www.microsoft.com/en-us/
  audit20:
    runs-on: ubuntu-20.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@test
      with:
        egress-policy: audit
        
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - run: sleep 20
    - run: curl -X GET https://www.google.com
    - run: sleep 20
    - run: curl -X GET https://api.github.com
    - run: sleep 20
    - run: curl -X GET https://www.google.com
    - run: sleep 20
    - run: curl -X GET https://www.microsoft.com/en-us/
