name: HardenRunner Test
on: 
  workflow_dispatch
jobs:
  block22:
    runs-on: ubuntu-22.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
      with:
        egress-policy: block
        allowed-endpoints: >
          github.com:443
          www.google.com:443
          api.github.com:443
          www.microsoft.com:443
    - uses: actions/checkout@v3
    - run: sleep 20
    - run: curl -X GET https://www.google.com
    - run: sleep 20
    - run: curl -X GET https://api.github.com
    - run: sleep 20
    - run: curl -X GET https://www.google.com
    - run: sleep 20
    - run: curl -X GET https://www.microsoft.com/en-us/
  block20:
    runs-on: ubuntu-20.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
      with:
        egress-policy: block
        allowed-endpoints: >
          github.com:443
          www.google.com:443
          api.github.com:443
          www.microsoft.com:443
    - uses: actions/checkout@v3
    - run: sleep 20
    - run: curl -X GET https://www.google.com
    - run: sleep 20
    - run: curl -X GET https://api.github.com
    - run: sleep 20
    - run: curl -X GET https://www.google.com
    - run: sleep 20
    - run: curl -X GET https://www.microsoft.com/en-us/
  audit22:
    runs-on: ubuntu-22.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
      with:
        egress-policy: audit
        
    - uses: actions/checkout@v3
    - run: sleep 20
    - run: curl -X GET https://www.google.com
    - run: sleep 20
    - run: curl -X GET https://api.github.com
    - run: sleep 20
    - run: curl -X GET https://www.google.com
    - run: sleep 20
    - run: curl -X GET https://www.microsoft.com/en-us/
  audit20:
    runs-on: ubuntu-20.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
      with:
        egress-policy: audit
        
    - uses: actions/checkout@v3
    - run: sleep 20
    - run: curl -X GET https://www.google.com
    - run: sleep 20
    - run: curl -X GET https://api.github.com
    - run: sleep 20
    - run: curl -X GET https://www.google.com
    - run: sleep 20
    - run: curl -X GET https://www.microsoft.com/en-us/
