# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: "build / docker"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Harden Runner
        uses: step-security/harden-runner@d8b192edce5dfee4b4af7a1575f9ef0802208694 # int
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443

      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo ${{ job.status }}
          sleep 10

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo ${{ job.status }}
  build1:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      name: "build / docker1"
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Harden Runner
          uses: step-security/harden-runner@d8b192edce5dfee4b4af7a1575f9ef0802208694 # int
          with:
            disable-sudo: true
            egress-policy: block
            allowed-endpoints: >
              github.com:443

        - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

        # Runs a single command using the runners shell
        - name: Run a one-line script
          run: |
            echo ${{ job.status }}
            sleep 10

        # Runs a set of commands using the runners shell
        - name: Run a multi-line script
          run: |
            echo Add other actions to build,
            echo test, and deploy your project.
            echo ${{ job.status }}
